---
- hosts: localhost
  become: true
  connection: ssh
  gather_facts: no
          
  tasks:
  - name: Install nginx
    apt: pkg=nginx state=installed update_cache=true
    notify: restart nginx

  - name: rename index file
    command: mv /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.backup
                                        
  - name: copy and rename index file
    command: mv /tmp/index.html /var/www/html/index.nginx-debian.html

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted enabled=yes
